# Generated by Django 5.1.4 on 2025-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_form',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
