# Generated by Django 5.1.4 on 2025-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0002_reg_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_form',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reg_form',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
