# Generated by Django 5.1.4 on 2025-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0003_alter_reg_form_age_alter_reg_form_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('propertytype', models.CharField(max_length=200)),
                ('prop', models.CharField(blank=True, choices=[('rent', 'RENT'), ('sale', 'SALE')], max_length=10, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
