# Generated by Django 5.1.5 on 2025-01-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0004_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.reg_form'),
        ),
    ]
