# Generated by Django 5.1.5 on 2025-01-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0005_remove_property_name_alter_property_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
