# Generated by Django 5.1.5 on 2025-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0007_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interseted',
            field=models.BooleanField(default=False),
        ),
    ]
