# Generated by Django 5.1.5 on 2025-02-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0008_property_interseted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='interseted',
        ),
    ]
