# Generated by Django 5.1.5 on 2025-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0010_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
