# Generated by Django 5.1.5 on 2025-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0011_alter_interested_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_form',
            name='confirmpwd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
