# Generated by Django 5.1.5 on 2025-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0014_contactmessage_replied_at_contactmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
