# Generated by Django 5.1.5 on 2025-03-03 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0017_forumcategory_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='best_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for', to='landhub.answer'),
        ),
        migrations.CreateModel(
            name='AnswerUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.reg_form')),
            ],
            options={
                'unique_together': {('user', 'answer')},
            },
        ),
    ]
