# Generated by Django 5.1.5 on 2025-03-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.reg_form')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
