# Generated by Django 5.1.5 on 2025-03-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0020_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('pwd', models.CharField(max_length=30)),
                ('confirmpwd', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buyer_images/')),
                ('buyer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('preferred_categories', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_history', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
            },
        ),
    ]
