# Generated by Django 5.1.5 on 2025-03-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0022_remove_buyer_confirmpwd_alter_buyer_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='landhub.buyer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.property')),
            ],
            options={
                'unique_together': {('buyer', 'property')},
            },
        ),
    ]
