# Generated by Django 5.1.5 on 2025-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0025_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
