# Generated by Django 5.1.5 on 2025-04-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landhub', '0029_buyerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.buyer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landhub.reg_form')),
            ],
        ),
    ]
